name: Security checks
on:
  pull_request:
    paths:
      - package.json
      - yarn.lock
  push:
    branches:
      - main

permissions: {}

jobs:
  security:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable --check-cache --check-resolutions

      - name: Check project packages for deprecated
        run: yarn npm audit --all --severity moderate

      - name: Check all packages for vulnerabilities
        run: yarn npm audit --all --recursive --severity high
